from sites.CHDBits import *
from sites.HDChina import *
from sites.HDSky import *
from sites.MTeam import *
from sites.OpenCD import *
from sites.OurBits import *
from sites.SSD import *
from sites.TTG import *
from sites.U2 import *
